# Spring properties
spring:
  application:
     name: driver-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 8888   # HTTP (Tomcat) port